### ISSUE TITLE
AttributeError: module 'pygetwindow' has no attribute 'getAllWindows'

### ISSUE THREAD

**Issue by shadowzoom** [victordlp8/OreMining#3]
```
willi@Willis-MacBook-Pro OreMining % python3 keeper.py
thread 'main' panicked at /Users/willi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.4/src/main.rs:214:59:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error executing command: Command 'ore --keypair ore_keypair.json rewards' returned non-zero exit status 101.
Traceback (most recent call last):
  File "/Users/willi/Desktop/OreMining/keeper.py", line 135, in <module>
    main()
  File "/Users/willi/Desktop/OreMining/keeper.py", line 97, in main
    initial_windows = pygw.getAllWindows()
                      ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pygetwindow' has no attribute 'getAllWindows'
willi@Willis-MacBook-Pro OreMining % python3 keeper.py                   
thread 'main' panicked at /Users/willi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ore-cli-0.4.4/src/main.rs:214:59:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error executing command: Command 'ore --keypair ore_keypair.json rewards' returned non-zero exit status 101.
Traceback (most recent call last):
  File "/Users/willi/Desktop/OreMining/keeper.py", line 135, in <module>
    main()
  File "/Users/willi/Desktop/OreMining/keeper.py", line 97, in main
    initial_windows = pygw.getAllWindows()
                      ^^^^^^^^^^^^^^^^^^
AttributeError: module 'pygetwindow' has no attribute 'getAllWindows'
```

**Comment by tomiock** [comment]
This repo is meant for personal use and we do not plan to make it Unix compatible. Fork if you have any issues.
We are sorry for the inconvenience.

See this issue for more information #5 

You may try to use https://github.com/Kalmat/PyWinCtl
