### ISSUE TITLE
No section: 'ORE' KeyError: 'ORE'

### ISSUE THREAD

**Issue by bashar1988** [victordlp8/OreMining#8]
No section: 'ORE'
KeyError: 'ORE'

During handling of the above exception, another exception occurred:

  File "C:\Windows\System32\OreMining-main\keeper.py", line 18, in __init__
    self.priority_fee = int(config.get("ORE", "priority_fee"))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Windows\System32\OreMining-main\keeper.py", line 160, in main
    ORE = Ore()
          ^^^^^
  File "C:\Windows\System32\OreMining-main\keeper.py", line 216, in <module>
    main()
configparser.NoSectionError: No section: 'ORE'

could you please help

**Comment by bashar1988** [comment]
C:\Windows\System32\OreMining-main>python keeper.py
Traceback (most recent call last):
  File "C:\Windows\System32\OreMining-main\keeper.py", line 216, in <module>
    main()
  File "C:\Windows\System32\OreMining-main\keeper.py", line 160, in main
    ORE = Ore()
          ^^^^^
  File "C:\Windows\System32\OreMining-main\keeper.py", line 20, in __init__
    self.keypairs_path = config.get("ORE", "keypairs_path")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahmad\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 1132, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'ORE'

C:\Windows\System32\OreMining-main>pause

**Comment by victordlp8** [comment]
do you have the updated config.ini file?

**Comment by bashar1988** [comment]
yes i have update it 
[ORE]
keypairs_path = "ore_keypair.json"

; RPC used for the mining operations and other ore-cli commands.
; If you want to add more and alternate please do it like this [rpc1, rpc2, rpc3, rpc4] instead of just [rpc1].
rpc = my rpc

; Priority fee used for the mining operations and other ore-cli commands.
priority_fee = 1000

; Number of threads used per instance of a miner.
threads = 4

[MINERS]
; Number of parallel miners that will be deployed per keypair.
parallel_miners = 3

; Delay between waves of miners in seconds.
miners_phase = 60

; Number of miners per wave of deployment.
miners_wave = 2

**Comment by bashar1988** [comment]
thx you can close it i Figure it out and now its working thank you
